package com.cys.boot.service;
import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.cys.boot.entity.Address;
import com.cys.boot.entity.User;
/**
 * @description user's session==>{user,(! storeidList if user is a css)
 * ,sc,sciMap} 
 * @author ChenYongSheng
 * @date 2022/8/6
 */
public interface UserService {
	User getUser(long id);
	User getUserByPhoneNumber(long phoneNumber);
	void insertUser(User user);
	void updateUser(User user);
	void deleteUser(User user);

	

	/**
	 * init user session info need
	 * @param hsr will init to set session.(user)->(sc)->(sciMap)
	 * @author Chenyongsheng
	 */
	void initUserInfoIntoSession(HttpServletRequest hsr);
	
	
	void initSellerAndCssIntoSeesion(HttpServletRequest hsr);

	
	
	
	/**
	 * verify user phoneNumber and pswd
	 * @param user with phoneNumber and pswd
	 * @return this user(got from mysql) if he exists; 
	 * @author Chenyongsheng
	 */
	User verify(User user);
	
	
	
	/** 
	 * need  to verify user account by phoneNumber and pswd.
	 * @param json {phoneNumber,pswd}
	 * @author Chenyongsheng
	 * @return 1 if ok. 0 if verify failed
	 */
	int login(HttpServletRequest hsr, String json,HttpServletResponse hsrp);
	
	
	
	/**
	 * if user forgets his pswd, or chooses login by message.
	 * phoneNumber will be send to third parties
	 * @param phoneNumber
	 * @author Chenyongsheng
	 * @return verify code will be compared with user's to js
	 */
	String loginByPhoneMessage(long phoneNumber);

	
	/**
	 * verify code is generated by random (4), and is saved in imp field.
	 * @return code
	 * @author Chenyongsheng
	 */
	String getVerifyCode();
	
	
/**
 * register1 need staged user phoneNumber, pswd, and check if user
 * already exist.
 * @param json {user}
 * @return 1 if user doesn't exist in mysql
 * @author Chenyongsheng
 */
	int register1(String json);
	
	
	
	/**
	 * dispatchs third party api to send message vc to user , stage the
	 * code 
	 * @author Chenyongsheng
	 */
	void register2();
	
	
	
	/**
	 * receive mvc user input, if staged mvc=mvc, register successfully, 
	 * then insert user.
	 * @param mvc message verify code
	 * @return 1 if staged mvc=mvc
	 * @author Chenyongsheng
	 */
	int register3(String mvc);
	
	
	
	/**
	 * authentication need user's idNumber, face img.
	 * @param json 
	 * @author Chenyongsheng
	 */
	void realNameAuthentication(String json);
	
	

	Address getAddress(long id);
	ArrayList<Address> getAddressByUserId(HttpServletRequest hsr);
	String getDefaultAddress(long userId);
	Address addAddress(HttpServletRequest hsr,String json);
	void deleteAddresses(HttpServletRequest hsr,String listjson);
	void setDefaultAddress(HttpServletRequest hsr,long aid);
	/**
	 * exe after session destroying, address into mysql
	 * @param hsr
	 */
	void flushAddresses(User user);
	
	
	
	
}
